### ISSUE TITLE
js作用域 | 菜鸡三人组

### ISSUE THREAD

**Issue by ghter123** [ghter123/ghter123.github.io#8]
https://ghter123.github.io/2019/02/28/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8BJavaScript%E5%9F%BA%E7%A1%80/js%E4%BD%9C%E7%94%A8%E5%9F%9F/ 

 函数作用域和块作用域函数作用域1234567function test ()&#123;    var a = 1;    console.log ("函数内的a：" + a);&#125;test();//1console.log( a );//ReferenceError: a is not defined  由代码可看出，函数test内部是可以访问到a的值的，在函数外直接访问a的话会报错：

**Comment by ghter111** [comment]
很棒
